### ISSUE TITLE
register iax2

### ISSUE THREAD

**Issue by mohamadtay** [Apprpt-Central/pyIAX-Register#1]
hi sir . 
how to make register iax2 
with user and password  . can u give me a sample code  ?!

**Comment by coolacid** [comment]
Thanks for your interest!  This is still a bit of a work in progress. 

Right now, you would need to write your own register module, and load it in the threaded_server.py 

See: https://github.com/Apprpt-Central/pyIAX-Register/blob/main/threaded_server.py#L4
And: https://github.com/Apprpt-Central/pyIAX-Register/blob/main/register/dummy.py

Eventually, I'll have a registration handler that will take a `user:password` formatted text file and approve registrations based on that. 

While you're waiting, I'd be interested in knowing how you found the code, and what your goals are. I'm looking for this information so that I can see other peoples use cases and try and include those as I work through this.

**Comment by mohamadtay** [comment]
I work as a programmer
But little experience with Python. This is a project via Freelancer

**Comment by coolacid** [comment]
Ah, Unfortunately, you'll need to wait for a while as I work thru the code, but an example registration system is in the dummy registration.

**Comment by mohamadtay** [comment]
Thank you very much, I give it a try. For two weeks I have been trying to create this program and I cannot

**Comment by coolacid** [comment]
What is your client trying to do? Any details you can share? Maybe I can give you a hint on if this will even work.

**Comment by mohamadtay** [comment]
He just wants to create a program that does a phone
Registration and  call

**Comment by coolacid** [comment]
This project won't ever handle calls, sorry. Right now, the only bits that are implemented is handling IAX2 registration requests.

**Comment by mohamadtay** [comment]
do u have skype to help me ?

**Comment by mohamadtay** [comment]
my server is register in other program like zoiper 
but in your program i have this error
  
File "threaded_server.py", line 38, in __init__
    socketserver.UDPServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

**Comment by coolacid** [comment]
Do you already have something listening on the port?

**Comment by mohamadtay** [comment]
yes i have . i hope to call me on skype or any other program to help me

**Comment by coolacid** [comment]
Sorry, I don't provide Phone Support.

**Comment by mohamadtay** [comment]
I got the problem
The program does not allow you to connect to any IP outside the network

**Comment by coolacid** [comment]
I don't know what to tell you, again, this is SERVER software, not a client.
